---
language: python

dist: trusty

services:
  - postgresql
  - redis-server
  - rabbitmq

python:
  - "3.5"

before_install: openssl aes-256-cbc -K $encrypted_b3c74f49840a_key -iv $encrypted_b3c74f49840a_iv -in secrets.py.enc -out pawprints/secrets.py -d

install: 
  - pip install -r requirements.txt
  - pip install coverage
  - pip install codecov

before_script:
  - psql -c 'CREATE DATABASE pawprints;' -U postgres

script: coverage run manage.py test

after_script: codecov
